# -*- coding: utf-8 -*-
"""HW1 crm nutt

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmAhq0ly8dldO5bucvxlpzJpFoYwiSuH
"""

import matplotlib as mpl

!wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf


mpl.font_manager.fontManager.addfont('thsarabunnew-webfont.ttf')
mpl.rc('font', family='TH Sarabun New', size= 20)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import re

df = pd.read_csv("/content/drive/MyDrive/CRM/Customer Behaviors (Responses).csv")
df.head()

#df.info()

new_col = []
for c in df.columns :
  c = re.sub("[\[\]]+", '',c)
  if c == 'นอกเหนือจากรายการดังกล่าวแล้ว คุณมีความสนใจในเรื่องใดอีกบ้าง':
    c = 'ความสนใจอื่นๆ'
  elif 'คุณมีความสนใจในสิ่งเหล่านี้มากน้อยเพียงใด' in c:
    c = c.replace('คุณมีความสนใจในสิ่งเหล่านี้มากน้อยเพียงใด', 'สนใจ')
  elif 'คุณบริโภคสิ่งเหล่านี้บ่อยขนาดไหน' in c:
    c = c.replace('คุณบริโภคสิ่งเหล่านี้บ่อยขนาดไหน', 'บริโภค')
  else:
    print('skip :',c)
  c = c.replace(' ','_')
  new_col.append(c)
df.columns = new_col
print('Example of column names')
print(df.columns[:10])
print(df.columns[-10:])

col_interest = [ c for c in df.columns if 'สนใจ' in c and c != 'นอกเหนือจากรายการดังกล่าวแล้ว_คุณมีความสนใจในเรื่องใดอีกบ้าง']
col_consume = [ c for c in df.columns if 'บริโภค' in c]
col_free_text = ['ความสนใจอื่นๆ']

print(f'col_interest has total {len(col_interest)} cols')
print(col_interest,'\n')
print(f'col_consume has total {len(col_consume)} cols')
print(col_consume,'\n')
print(f'col_free_text has total {len(col_free_text)} col')
print(col_free_text)

df.head()



replace_likert_interest = {
    'ไม่สนใจอย่างมากที่สุด' : -3,
    'ไม่สนใจอย่างมาก' : -2,
    'ไม่สนใจ' : -1,
    'เฉยๆ' : 0,
    'สนใจ' : 1,
    'สนใจอย่างมาก' : 2,
    'สนใจอย่างมากที่สุด' : 3}

replace_likert_consume = {
    'แทบไม่ได้บริโภคเลย': 0,
    'หลายเดือนครั้ง' : 1,
    'เดือนละ 2-3 ครั้ง' : 2,
    'เดือนละครั้ง' : 3,
    'อาทิตย์ละครั้ง' : 4,
    'แทบทุกวัน' : 5}

df[col_interest] = df[col_interest].replace(replace_likert_interest)
df[col_consume] = df[col_consume].replace(replace_likert_consume)
df.head(10)

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
# %matplotlib inline


df1 = df[['บริโภค_เสื้อผ้าแฟชั่น','บริโภค_แต่งหน้า','บริโภค_skincare_บำรุงผิว','บริโภค_การออกกำลังกาย',
         'บริโภค_การเล่นเกมส์','บริโภค_การท่องเที่ยว','บริโภค_การอ่านหนังสือ','บริโภค_การอ่านบทความ_Online','บริโภค_การเรียน_e-learning', 'บริโภค_ดู_Series','บริโภค_ดูหนัง','บริโภค_ดู_Youtube','บริโภค_ดู_Netflix','บริโภค_Content_ด้านบันเทิง','บริโภค_Content_เกี่่ยวกับเกมส์',
         'บริโภค_Content_เกี่ยวกับการ_review_ร้านอาหาร','บริโภค_Content_เกี่ยวกับการท่องเที่ยว','บริโภค_Content_เกี่ยวกับการแต่งบ้าน','บริโภค_Content_เกี่ยวกับการโทรทัศน์','บริโภค_Content_เกี่ยวกับละคร','บริโภค_Content_เกี่ยวกับการเมือง']]
#print(df1)

plt.figure(figsize=(10, 10))
sns.heatmap(df1.corr(), annot=True, cmap='coolwarm')

"""

1.   คนชอบแต่งหน้าก็จะบริโภคskin care
2.   คนชอบเล่นเกมก็จะบริโภค content เกี่ยวกับเกมส์
3.   คนชอบดู series กับ ดูหนัง ทาง netflix
4.   คนชอบดูcontent เกี่ยวกับ review อาหารก็ค่อนข้างจะชอบดู content เกี่ยวกับการท่องเที่ยวด้วย
5.   คนดูชอบดูละครทางโทรทัศน์









"""

fig = plt.gcf()
fig.set_size_inches(15, 20)
# Create a figure with 2x2 subplot layout and make the top left subplot active
plt.subplot(9,2,1) # อาหารญี่ปุ่น
plt.boxplot(df["สนใจ_อาหารญี่ปุ่น"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_อาหารญี่ปุ่น")
plt.subplot(9,2,2) 
plt.boxplot(df["บริโภค_อาหารญี่ปุ่น"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_อาหารญี่ปุ่น")

plt.subplot(9,2,3) # อาหารไทย
plt.boxplot(df["สนใจ_อาหารไทย"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_อาหารไทย")
plt.subplot(9,2,4) 
plt.boxplot(df["บริโภค_อาหารไทย"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_อาหารไทย")

plt.subplot(9,2,5) # อาหารอีสาน
plt.boxplot(df["สนใจ_อาหารอีสาน"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_อาหารอีสาน")
plt.subplot(9,2,6) 
plt.boxplot(df["บริโภค_อาหารอีสาน"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_อาหารอีสาน")

plt.subplot(9,2,7) # อาหารจีน
plt.boxplot(df["สนใจ_อาหารจึน"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_อาหารจีน")
plt.subplot(9,2,8) 
plt.boxplot(df["บริโภค_อาหารจึน"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_อาหารจีน")

plt.subplot(9,2,9) # อาหารสุขภาพ
plt.boxplot(df["สนใจ_อาหารสุขภาพ"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_อาหารสุขภาพ")
plt.subplot(9,2,10) 
plt.boxplot(df["บริโภค_อาหารสุขภาพ"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_อาหารสุขภาพ")

plt.subplot(9,2,11) # อาหารบุฟเฟ่
plt.boxplot(df["สนใจ_บุฟเฟต์"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_บุฟเฟต์")
plt.subplot(9,2,12) 
plt.boxplot(df["บริโภค_บุฟเฟต์"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_บุฟเฟต์")

plt.subplot(9,2,13) # ชาบู
plt.boxplot(df["สนใจ_ชาบูชาบู"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_ชาบูชาบู")
plt.subplot(9,2,14) 
plt.boxplot(df["บริโภค_ชาบูชาบู"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_ชาบูชาบู")

plt.subplot(9,2,15) # อาหารปิ้งย่าง
plt.boxplot(df["สนใจ_ปิ้งย่าง"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_ปิ้งย่าง")
plt.subplot(9,2,16) 
plt.boxplot(df["บริโภค_ปิ้งย่าง"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_ปิ้งย่าง")

plt.subplot(9,2,17) # อาหารเบีย
plt.boxplot(df["สนใจ_เหล้าเบียร์"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_เหล้าเบียร์")
plt.subplot(9,2,18) 
plt.boxplot(df["บริโภค_เหล้าเบียร์"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_เหล้าเบียร์")




plt.tight_layout()
plt.show()

"""กลุ่มตัวอย่างค่อนข้างจะสนใจและบริโภคอาหารญี่ปุ่น ไทย อีสาน บ่อยน่าจะเพราะหาทานง่าย ส่วนอาหารจีนค่อยข้างเฉยๆและบริโภคไม่บ่อยมาก
และระหว่างชาบูกับปิ้งย่างดูแล้วค่อนข้างสนใจชาบูมากกว่าแต่กลับบริโภคปิ้งย่างมากกว่า(อาจเพราะหมายรวมหมูกะทะไปด้วย ราคาถูกกว่ากินได้บ่อยกว่า)
ซึ่งกรุ๊ปนี้ไม่ค่อยสนใจเหล้าเบียและก็ทานไม่บ่อย
"""

fig = plt.gcf()
fig.set_size_inches(15, 25)
# Create a figure with 2x2 subplot layout and make the top left subplot active
plt.subplot(13,2,1) # อาหารญี่ปุ่น
plt.boxplot(df["สนใจ_เสื้อผ้าแฟชั่น"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_เสื้อผ้าแฟชั่น")
plt.subplot(13,2,2) 
plt.boxplot(df["บริโภค_เสื้อผ้าแฟชั่น"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_เสื้อผ้าแฟชั่น")

plt.subplot(13,2,3) # อาหารจีน
plt.boxplot(df["สนใจ_แต่งหน้า"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_แต่งหน้า")
plt.subplot(13,2,4) 
plt.boxplot(df["บริโภค_แต่งหน้า"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_แต่งหน้า")

plt.subplot(13,2,5) # อาหารจีน
plt.boxplot(df["สนใจ_skincare_บำรุงผิว"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_skincare_บำรุงผิว")
plt.subplot(13,2,6) 
plt.boxplot(df["บริโภค_skincare_บำรุงผิว"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_skincare_บำรุงผิว")

plt.subplot(13,2,7) # อาหารจีน
plt.boxplot(df["สนใจ_การออกกำลังกาย"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_การออกกำลังกาย")
plt.subplot(13,2,8) 
plt.boxplot(df["บริโภค_การออกกำลังกาย"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_การออกกำลังกาย")

plt.subplot(13,2,9) # อาหารจีน
plt.boxplot(df["สนใจ_การเล่นเกมส์"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_การเล่นเกมส์")
plt.subplot(13,2,10) 
plt.boxplot(df["บริโภค_การเล่นเกมส์"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_การเล่นเกมส์")

plt.subplot(13,2,11) # อาหารจีน
plt.boxplot(df["สนใจ_การท่องเที่ยว"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_การท่องเที่ยว")
plt.subplot(13,2,12) 
plt.boxplot(df["บริโภค_การท่องเที่ยว"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_การท่องเที่ยว")

plt.subplot(13,2,13) # อาหารจีน
plt.boxplot(df["สนใจ_การอ่านหนังสือ"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_การอ่านหนังสือ")
plt.subplot(13,2,14) 
plt.boxplot(df["บริโภค_การอ่านหนังสือ"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_การอ่านหนังสือ")

plt.subplot(13,2,15) # อาหารจีน
plt.boxplot(df["สนใจ_การอ่านบทความ_Online"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_การอ่านบทความ_Online")
plt.subplot(13,2,16) 
plt.boxplot(df["บริโภค_การอ่านบทความ_Online"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_การอ่านบทความ_Online")

plt.subplot(13,2,17) # อาหารจีน
plt.boxplot(df["สนใจ_การเรียน_e-learning"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_การเรียน_e-learning")
plt.subplot(13,2,18) 
plt.boxplot(df["บริโภค_การเรียน_e-learning"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_การเรียน_e-learning")

plt.subplot(13,2,19) # อาหารจีน
plt.boxplot(df["สนใจ_ดู_Series"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_ดู_Series")
plt.subplot(13,2,20) 
plt.boxplot(df["บริโภค_ดู_Series"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค__ดู_Series")

plt.subplot(13,2,21) # อาหารจีน
plt.boxplot(df["สนใจ_ดูหนัง"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_ดูหนัง")
plt.subplot(13,2,22) 
plt.boxplot(df["บริโภค_ดูหนัง"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_ดูหนัง")

plt.subplot(13,2,23) # อาหารจีน
plt.boxplot(df["สนใจ_ดู_Youtube"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_ดู_Youtube")
plt.subplot(13,2,24) 
plt.boxplot(df["บริโภค_ดู_Youtube"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_ดู_Youtube")

plt.subplot(13,2,25) # อาหารจีน
plt.boxplot(df["สนใจ_ดู_Netflix"])
plt.xlabel("")
plt.ylabel('ระดับความสนใจ')
plt.title("สนใจ_ดู_Netflix")
plt.subplot(13,2,26) 
plt.boxplot(df["บริโภค_ดู_Netflix"])
plt.xlabel("")
plt.ylabel('ระดับการบริโภค')
plt.title("บริโภค_ดู_Netflix")


plt.tight_layout()
plt.show()

"""กลุ่มตัวอย่างไม่ค่อยสนใจแฟชั่นไม่ค่อยแต่งหน้าแต่ค่อนข้างจะดูแลตัวเองเพราะสนใจและบริโภคskincareกับออกกำลังกายบ่อย

ชอบเล่นเกมและเล่นบ่อยด้วย และชอบเที่ยวแต่ไม่ค่อยมีเวลาเที่ยว(อาจจะเอาเวลาไปเล่นเกมหมด)

ชอบการดูserie ดูหนัง youtube netflix ซึ่งเหมือนว่าจะเป็นกิจวัฒประจำวันได้เลย

"""